name: 'my_ny_taxi_project'
version: '1.0.0'
config-version: 2

# Profile này dbt cloud sẽ tự xử lý, cứ để default
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  my_ny_taxi_project:
    # Config model mặc định
    example:
      +materialized: view
